version: '3.8'  
  
services:  
  app:  
    build: .  
    ports:  
      - "4000:4000"  
    environment:  
      - DATABASE_URL=mongodb://mongo:27017/your-database-name  
    depends_on:  
      - mongo  
  
  mongo:  
    image: mongo:latest  
    ports:  
      - "8080:8025"  
    volumes:  
      - mongo-data:/data/db  
  
volumes:  
  mongo-data:  